"""add employees and transaction.employee_id

Revision ID: 84daf2f3e989
Revises: ad84796ecd5b
Create Date: 2026-05-12 16:04:18.999023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84daf2f3e989'
down_revision: Union[str, Sequence[str], None] = 'ad84796ecd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.Enum('permanent', 'contract', 'casual', 'intern', name='employmenttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('kra_pin', sa.String(length=20), nullable=True),
    sa.Column('nhif_number', sa.String(length=20), nullable=True),
    sa.Column('nssf_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pay_frequency', sa.Enum('monthly', 'semi_monthly', 'weekly', 'biweekly', name='payfrequency'), nullable=False),
    sa.Column('pay_day_config', sa.JSON(), nullable=False),
    sa.Column('default_account_id', sa.Integer(), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('last_paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_employee_id', 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_employee_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_employee_id'))
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
