"""add recurring transactions

Revision ID: 906c90757d44
Revises: f11612c9bd92
Create Date: 2026-05-12 23:51:34.752613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906c90757d44'
down_revision: Union[str, Sequence[str], None] = 'f11612c9bd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='categorytype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'yearly', name='recurringfrequency'), nullable=False),
    sa.Column('day_config', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('occurrences_count', sa.Integer(), nullable=False),
    sa.Column('last_generated_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_recurring_transaction_id'), ['recurring_transaction_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_recurring_transaction_id', 'recurring_transactions', ['recurring_transaction_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_recurring_transaction_id'))
        batch_op.drop_column('recurring_transaction_id')

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_category_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_account_id'))

    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
