"""Add account_id to transactions

Revision ID: ad84796ecd5b
Revises: 725b1fdc6780
Create Date: 2026-05-12 02:29:05.614901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad84796ecd5b'
down_revision: Union[str, Sequence[str], None] = '725b1fdc6780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
