"""make employee pay_amount nullable

Revision ID: b16b884079e9
Revises: 84daf2f3e989
Create Date: 2026-05-12 17:47:43.453597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16b884079e9'
down_revision: Union[str, Sequence[str], None] = '84daf2f3e989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('pay_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('pay_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###
